src/Entity/Paid.php
<?php

namespace App\Entity;

use App\Enum\PaidEnum;
use App\Owner\UserStudentOwnerInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PaidRepository;
use ApiPlatform\Metadata as Metadata;
use App\Controller\APIs\PaidStudentController;
use Symfony\Component\HttpFoundation\File\File;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: PaidRepository::class)]
#[Metadata\ApiResource(
    security: "is_granted('ROLE_USER')",
    operations: [
        new Metadata\Get(
            normalizationContext: [
                'groups' => [
                    'read:paid:item',
                ]
            ],
        ),
        new Metadata\Post(
            uriTemplate: '/verify-response-qrcode/{token}',
            controller: PaidStudentController::class,
            normalizationContext: [
                'groups' => [
                    'read:paid:state',
                ]
            ],
        ),
        new Metadata\GetCollection(
            normalizationContext: [
                'groups' => [
                    'read:paid:collection',
                ]
            ],
        )
    ],
), Metadata\ApiFilter(
    SearchFilter::class,
    properties: [
        'id' => 'partial',
        'name' => 'partial',
        'alias' => 'partial',
        'created_at' => 'partial'
    ]
)]
#[Vich\Uploadable]
class Paid implements UserStudentOwnerInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
        ]
    )]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'paids')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
            'read:level:item',
        ]
    )]
    private ?Student $student = null;

    #[ORM\ManyToOne(inversedBy: 'paids')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
        ]
    )]
    private ?Level $level = null;

    #[ORM\Column(enumType: PaidEnum::class)]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
            'read:level:item'
        ]
    )]
    private ?PaidEnum $state = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
        ]
    )]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(
        [
            'read:paid:item',
        ]
    )]
    private ?\DateTimeInterface $updated_at = null;

    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
            'read:level:item',
        ]
    )]
    public ?string $contentUrl = null;

    #[Vich\UploadableField(mapping: "qrcode_slip", fileNameProperty: "filePath")]
    public ?File $file = null;

    #[ORM\Column(nullable: true)]
    public ?string $filePath = null;

    #[ORM\Column(length: 255)]
    #[Groups(
        [
            'read:paid:collection',
            'read:paid:item',
            'read:level:item',
        ]
    )]
    private ?string $token = null;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
        $this->state = PaidEnum::NO_PAID;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getState(): ?PaidEnum
    {
        return $this->state;
    }

    public function setState(PaidEnum $state): static
    {
        $this->state = $state;

        return $this;
    }
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }
    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getContentUrl(): ?string
    {
        return $this->contentUrl;
    }

    public function setContentUrl(?string $contentUrl): static
    {
        $this->contentUrl = $contentUrl;

        return $this;
    }
    public function getFile(): File|null
    {
        return $this->file;
    }
    public function setFile(?File $file): static
    {
        $this->file = $file;

        if ($file) {
            // Mettez à jour `updated_at` pour que VichUploader puisse détecter le changement
            $this->updated_at = new \DateTime();
        }

        return $this;
    }

    public function getFilePath(): string|null
    {
        return $this->filePath;
    }

    public function setFilePath(?string $filePath): static
    {
        $this->filePath = $filePath;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): static
    {
        $this->token = $token;

        return $this;
    }
}

src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata as Metadata;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: PaymentRepository::class)]
#[Metadata\ApiResource(
    operations: [
        new Metadata\Get(
            normalizationContext: [
                'groups' => [
                    'read:payment:item',
                ]
            ],
        ),
        new Metadata\GetCollection(
            normalizationContext: [
                'groups' => [
                    'read:payment:collection',
                ]
            ],
        )
    ],
), Metadata\ApiFilter(
    SearchFilter::class,
    properties: [
        'id' => 'partial',
        'student' => 'partial',
        'level' => 'partial',
        'amount' => 'partial',
        'installment' => 'partial',
        'created_at' => 'partial'
    ]
)]
class Payment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'payments')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?Student $student = null;

    #[ORM\ManyToOne(inversedBy: 'payments')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?Amount $amount = null;

    #[ORM\ManyToOne(inversedBy: 'payments')]
    #[ORM\JoinColumn(nullable: true)]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?Installment $installment = null;

    #[ORM\ManyToOne(inversedBy: 'payments')]
    #[ORM\JoinColumn()]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?Level $level = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?\DateTimeInterface $payment_at = null;

    #[ORM\Column]
    #[Groups(
        [
            'read:payment:collection',
            'read:payment:item',
        ]
    )]
    private ?bool $paid = null;

    public function __construct()
    {
        $this->paid = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getAmount(): ?Amount
    {
        return $this->amount;
    }

    public function setAmount(?Amount $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getInstallment(): ?Installment
    {
        return $this->installment;
    }

    public function setInstallment(?Installment $installment): static
    {
        $this->installment = $installment;

        return $this;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getPaymentAt(): ?\DateTimeInterface
    {
        return $this->payment_at;
    }

    public function setPaymentAt(\DateTimeInterface $payment_at): static
    {
        $this->payment_at = $payment_at;

        return $this;
    }

    public function isPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(bool $paid): static
    {
        $this->paid = $paid;

        return $this;
    }
}

src/Controller/Base/WelcomeController.php
<?php


namespace App\Controller\Base;

use App\Repository\AmountRepository;
use App\Repository\QuizRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class WelcomeController extends AbstractController
{
  public function __construct(
    private QuizRepository $quizRepository,
    private AmountRepository $amountRepository,
  ) {}

  #[Route('/', name: 'welcome')]
  public function index(): Response
  {
    return $this->render('welcome/welcome.html.twig', [
      'quizzes' => $this->quizRepository->findBy(['featured' => true]),
      'amounts' => $this->amountRepository->findByCurrentYearAcademic(),
    ]);
  }
}

src/Controller/WelcomeController.php
<?php


namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class WelcomeController extends AbstractController
{
  #[Route('/', name: 'welcome')]
  public function index(): Response
  {
    return $this->render('welcome/welcome.html.twig');
  }
}

templates/welcome/_amount.html.twig
<twig:Card>
  <div class="mb-2">
    <div class="max-w-lg mb-2">
      <h1 class="mb-3 text-sm font-semibold text-slate-700 dark:text-gray-300">
        Tranches que vous devez payé
      </h1>
    </div>
    <div class="mb-3">
      <twig:Table>
        <twig:TableHeader>
          <twig:TableRow>
            <twig:TableHead> Tranche </twig:TableHead>
            <twig:TableHead> Date d'écheance </twig:TableHead>
          </twig:TableRow>
        </twig:TableHeader>

        <twig:TableBody>
          {% for payment in payments %}
          <twig:TableRow>
            <twig:TableCell>
              {{ payment.installment.price|number_format(2, '.', ',') }} FC
            </twig:TableCell>
            <twig:TableCell>
              {{ payment.paymentAt.format('d-m-Y H:i') }}
            </twig:TableCell>
          </twig:TableRow>
          {% endfor %}
        </twig:TableBody>
      </twig:Table>
    </div>
    <div class="flex flex-col gap-3 max-w-sm">
      <div
        class="bg-gray-50 text-sm dark:bg-gray-400 p-2 rounded-md shadow-sm shadow-blue-500 font-semibold border border-r-blue-400">
        Total : {{ payments|calculateTotality|number_format(2, '.', ',') }} FC
      </div>
      {% set r = remainingTotality(amount.price, payments) %}

      {% if r > 0 %}
      <div
        class="bg-gray-50 text-sm dark:bg-gray-400 p-2 rounded-md shadow-sm shadow-red-500 font-semibold border border-r-red-400">
        Reste : {{ r|number_format(2, '.', ',') }} FC
      </div>
      {% endif %}
    </div>
  </div>
</twig:Card>

templates/welcome/_hero.html.twig
<div class="mx-auto max-w-2xl py-16">
  <div class="hidden sm:mb-8 sm:flex sm:justify-center">
    <a href=""
      class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
      Un communiquer a été publié <span aria-hidden="true">&rarr;</span>
    </a>
  </div>
  <div class="mx-auto max-w-2xl">
    <div class="text-center">
      <h1
        class="text-4xl font-extrabold tracking-tight md:text-5xl lg:text-6xl leading-snug text-transparent bg-clip-text bg-gradient-to-r from-slate-700 via-primary/60 to-black/70 mb-6">
        Quick Check
      </h1>
      <p class="mt-8 text-pretty text-lg  text-gray-700 sm:text-xl/8">
        Simplifiez la gestion de vos paiements académiques grâce à notre système innovant.
        Cette solution, basée sur des QR codes, rend le processus de paiement rapide, sécurisé et facile à utiliser.
      </p>
      <div class="mt-10 flex items-center justify-center gap-x-6">

        <a href=""
          class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-primary hover:bg-primary/90 focus:ring-4 focus:ring-primary/50 dark:focus:ring-primary/60">
          <div class="flex items-center gap-3">
            Apprendre en plus
            <i class="bi bi-arrow-right"></i>
          </div>
        </a>
        <a href=""
          class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-gray-700 rounded-lg bg-gray-100 border hover:bg-gray-300 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
          <div class="flex items-center gap-3">
            Documentation
            <span aria-hidden="true">→</span>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

templates/welcome/_quiz.html.twig
{% for quiz in quizzes %}
<twig:Card class="hover:border-primary mb-4">
  <a href="{{ path('quiz.show', {id: quiz.id}) }}" class="block h-full w-full">
    <h2 class="mb-2 text-xl font-semibold text-gray-700 dark:text-gray-50">
      {{ quiz.request|u.truncate(80, '...') }}
    </h2>
    <p class="text-sm mb-2">
      {{ quiz.createdAt|ago }}
    </p>
    <p class="mt-3 text-description">
      {{ quiz.response|u.truncate(300, '...') }}
    </p>
  </a>
</twig:Card>
{% endfor %}

templates/welcome/welcome.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "Page d'accueil" %}

{% block body %}

{% include "welcome/_hero.html.twig" %}


<div class="container py-12">
  <div class="mx-auto max-w-4xl">
    <twig:WrapperSection title="Frais académique" description="
    Afin de garantir une expérience éducative de qualité et de soutenir les infrastructures universitaires, 
    le paiement des frais académiques est une étape essentielle dans le processus d'inscription et de suivi académique.
    ">
      <div class="flex flex-col gap-6">
        {% for amount in amounts %}
        <twig:Card>
          <h1
            class="mb-3 text-3xl font-extrabold tracking-tight md:text-4xl  leading-snug text-transparent bg-clip-text bg-gradient-to-r from-slate-700 via-primary/60 to-black/70">
            {{ amount.price|number_format(2, '.', ',') }} Fc
          </h1>
          <p class="text-base text-muted-foreground mb-2">
            {{ amount.programme.name }}
          </p>
          <twig:Table>
            <twig:TableHeader>
              <twig:TableRow>
                <twig:TableHead>Tranche(s) </twig:TableHead>
                <twig:TableHead> Priorité </twig:TableHead>
              </twig:TableRow>
            </twig:TableHeader>
            <twig:TableBody>
              {% for installment in amount.installments %}
              <twig:TableRow>
                <twig:TableCell>
                  {{ installment.price|number_format(2, '.', ',') }} Fc
                </twig:TableCell>

                <twig:TableCell>
                  <twig:Badge type="outline">
                    {{ installment.priority }}
                  </twig:Badge>
                </twig:TableCell>
              </twig:TableRow>
              {% endfor %}
            </twig:TableBody>
          </twig:Table>
        </twig:Card>
        {% endfor %}
      </div>
    </twig:WrapperSection>

    <twig:WrapperSection title="Questions fréquemment posées" description="
     Voici les réponses aux questions les plus courantes concernant les frais académiques. 
     Si vous ne trouvez pas votre réponse ici, n’hésitez pas à nous contacter.
     ">
      {% include "welcome/_quiz.html.twig" with {quizzes} %}
    </twig:WrapperSection>
  </div>
</div>
{% endblock %}